name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

# Force javascript actions to use Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      # Installs pnpm dynamically based on package.json (pnpm@11.10.0)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js Static Site
        run: pnpm build

      # Fixes GitHub Pages ignoring underscore folders (_next)
      - name: Create .nojekyll File
        run: touch ./out/.nojekyll

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4